#!/bin/bash
# SPDX-License-Identifier: MPL-2.0
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
SOURCE="${MUTTI_CONNECT_SOURCE:-$ROOT/../mutti/mutti/connect}"
python3 "$ROOT/Tools/MuttiConnect/verify-source.py" "$SOURCE"
PLATFORM="${1:-catalyst}"
ARCH="${2:-arm64}"
case "$PLATFORM" in
 catalyst) SDK=macosx; TRIPLE="$ARCH-apple-ios18.6-macabi"; SUFFIX=maccatalyst; GO_TARGET=ios;;
 ios) SDK=iphoneos; TRIPLE="$ARCH-apple-ios18.6"; SUFFIX=iphoneos; GO_TARGET=ios;;
 ios-simulator) SDK=iphonesimulator; TRIPLE="$ARCH-apple-ios18.6-simulator"; SUFFIX=iphonesimulator; GO_TARGET=ios;;
 tvos) SDK=appletvos; TRIPLE="$ARCH-apple-tvos18.6"; SUFFIX=appletvos; GO_TARGET=ios;;
 tvos-simulator) SDK=appletvsimulator; TRIPLE="$ARCH-apple-tvos18.6-simulator"; SUFFIX=appletvsimulator; GO_TARGET=ios;;
 *) echo 'Expected catalyst, ios, ios-simulator, tvos or tvos-simulator' >&2;exit 1;;
esac
case "$ARCH" in arm64) GO_ARCH=arm64;; x86_64) GO_ARCH=amd64;; *) exit 1;; esac
OUT="$ROOT/Tools/MuttiConnect/build/$SUFFIX/$ARCH"
mkdir -p "$OUT"
export MUTTI_APPLE_SDK="$SDK" MUTTI_APPLE_TRIPLE="$TRIPLE"
export GOOS="$GO_TARGET" GOARCH="$GO_ARCH" CGO_ENABLED=1
export CC="$ROOT/Tools/MuttiConnect/apple-clang.sh"
export CGO_CFLAGS="-target $TRIPLE" CGO_LDFLAGS="-target $TRIPLE"
(cd "$SOURCE" && go build -trimpath -buildmode=c-archive -o "$OUT/libmutti-connect.a" ./cmd/bridge)
cat > "$ROOT/XcodeConfig/MuttiConnect.local.xcconfig" <<'CONFIG'
// Generated by Tools/MuttiConnect/build.sh; binaries must exist for each built slice.
SWIFT_INCLUDE_PATHS = $(inherited) $(SRCROOT)/Tools/MuttiConnect/include
MUTTI_CONNECT_PLATFORM = $(PLATFORM_NAME)
MUTTI_CONNECT_PLATFORM[sdk=macosx*] = maccatalyst
LIBRARY_SEARCH_PATHS = $(inherited) $(SRCROOT)/Tools/MuttiConnect/build/$(MUTTI_CONNECT_PLATFORM)/$(CURRENT_ARCH)
OTHER_LDFLAGS = $(inherited) -lmutti-connect -lresolv -framework Security -framework Foundation -framework CoreFoundation
CONFIG
printf 'Built Mutti Connect: %s / %s\n' "$PLATFORM" "$ARCH"
